export const NOTIFICATION_TOAST_VISIBLE_MS = 8000;
export const NOTIFICATION_TOAST_EXIT_MS = 640;
export const NOTIFICATION_TOAST_MAX_VISIBLE = 4;
export const NOTIFICATION_REFETCH_INTERVAL_MS = 30_000;
